# Dependencies
markdown:         rdiscount
highlighter:         true

# Permalinks
permalink:        pretty

# Server
baseurl:          /
encoding:         UTF-8

# Globals
title: Seb Kay

# Exclude
exclude:
- config.codekit3
- assets/scss/
- assets/js/plugins/
- assets/js/app.js
- assets/js/jquery.custom.js
- assets/js/jquery.js
- assets/js/svg.js
