# Settings
url      : "https://sebkay.com"
encoding : UTF-8
future   : true

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Dependencies
highlighter : true
plugins     :
- jekyll-paginate
- jekyll-sitemap
- jekyll-autoprefixer

# Permalinks
baseurl   : /
permalink : /blog/:title/

# Globals
title         : Seb Kay
description   : Web Design & Development
paginate      : 6
paginate_path : "/blog/page/:num/"

# Markdown
markdown: kramdown

# Sass
sass:
  style: compressed
  sass_dir: assets/css/

# Autoprefixer
autoprefixer:
  browsers:
  - last 2 versions

# Include
include:
- _redirects

exclude:
- config.codekit3
- assets/js/third-party/
- assets/js/app.js
- assets/js/jquery.custom.js
