# Settings
url      : "https://sebkay.com"
encoding : UTF-8
future   : true

# Dependencies
highlighter : true
plugins     :
- jekyll-paginate
- jekyll-sitemap

# Permalinks
baseurl   : /
permalink : /blog/:title/

# Globals
title         : Seb Kay
description   : Web Design & Development
paginate      : 6
paginate_path : "/blog/page/:num/"

# Markdown
markdown: kramdown

sass:
  style: compressed
  sass_dir: assets/css/

# Include
include:
- _redirects

exclude:
- config.codekit3
- assets/js/third-party/
- assets/js/app.js
- assets/js/jquery.custom.js
