# Dependencies
markdown:         rdiscount
highlighter:         true
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Server
baseurl:          /
encoding:         UTF-8

# Globals
title: Seb Kay
paginate: 1
paginate_path: "/blog/page:num/"

# Exclude
exclude:
- config.codekit3
- assets/scss/
- assets/js/plugins/
- assets/js/app.js
- assets/js/jquery.custom.js
- assets/js/jquery.js
- assets/js/svg.js
