# Settings
url      : "https://sebkay.com"
encoding : UTF-8
future   : true

# Dependencies
markdown    : rdiscount
highlighter : true
plugins     :
- jekyll-paginate
- jekyll-sitemap

# Permalinks
baseurl   : /
permalink : /blog/:title/

# Globals
title         : Seb Kay
description   : Web Design & Development
paginate      : 5
paginate_path : "/blog/page:num/"

# Exclude
exclude:
- config.codekit3
- assets_dev/s

# Include
include:
- _redirects
